# Setup
title:        不染丶Space
description:  不愿染是与非，只做一个安安静静的小开发
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
author:
  name:       Xiaokun Jiang
  url:        https://jiangxiaokun.com

#Others
markdown: kramdown